name: movies_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.2.1
  flutter_rating_stars: ^1.0.3+4
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_dotenv: ^5.1.0
  tmdb_api: ^2.1.5
  dartz: ^0.10.1
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  iconify_flutter: ^0.0.5
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
