name: movies_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.2.1
  flutter_rating_stars: ^1.0.3+4
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  dartz: ^0.10.1
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  iconify_flutter: ^0.0.5
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
