List<Map<dynamic, dynamic>> categories = [
  {"id": "0", "name": "Todos"},
  {"id": "100", "name": "Series"},
  {"id": "28", "name": "Ação"},
  {"id": "12", "name": "Aventura"},
  {"id": "16", "name": "Animação"},
  {"id": "35", "name": "Comedia"},
  {"id": "80", "name": "Crime"},
  {"id": "99", "name": "Documentário"},
  {"id": "18", "name": "Drama"},
  {"id": "10751", "name": "Família"},
  {"id": "14", "name": "Fantasia"},
  {"id": "36", "name": "História"},
  {"id": "27", "name": "Terro"},
  {"id": "10402", "name": "Musical"},
  {"id": "9648", "name": "Mistério"},
  {"id": "10749", "name": "Romance"},
  {"id": "878", "name": "Ficção Científica"},
  {"id": "10770", "name": "Tv"},
  {"id": "53", "name": "Suspense"},
  {"id": "10752", "name": "Guerra"},
  {"id": "37", "name": "Faroeste"}
];
